//! Code generator for the canonical capability registry (CR-V2-B2-014).
//!
//! Generates four artifacts from `docs/dispatch/v2/source/capability-registry.json`:
//!
//! 1. Rust `enum CapabilityId` in `crates/video-capabilities/src/generated.rs`
//!    (committed artifact; excluded from rust-analyzer).
//! 2. TypeScript `bindings/ts/capabilities.ts` for the Studio frontend.
//! 3. JSON tool registry stub at `bindings/mcp/tool-registry.json` for the
//!    loopback MCP adapter (consumed in B2-025).
//! 4. CLI command surface (the `videoctl capabilities list` command in
//!    `crates/video-cli/` consumes this generator's stdout; the generator
//!    itself is independent so the CLI and Studio never duplicate logic).
//!
//! All four outputs are deterministic — same registry in, same bytes out —
//! so the codegen tests can compare byte-for-byte.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::registry::{CapabilityKind, RegistryDocument};

/// Schema id written into every generated artifact.
pub const GENERATOR_SCHEMA: &str = "cutright.capability_codegen/v1";

/// Errors raised by the codegen pipeline.
#[derive(Debug, thiserror::Error)]
pub enum CodegenError {
    /// Loader failed.
    #[error("codegen: failed to load registry: {0}")]
    Load(#[from] crate::error::RegistryError),
    /// I/O error writing an artifact.
    #[error("codegen: I/O error writing {path}: {source}")]
    Io {
        /// Output path that failed.
        path: PathBuf,
        /// Underlying I/O error.
        #[source]
        source: std::io::Error,
    },
    /// A capability id contained a character outside `[A-Za-z0-9_.]` so it
    /// could not be safely projected into a Rust/TypeScript identifier.
    #[error("codegen: capability_id {capability_id} contains non-identifier characters")]
    NonIdentifierSafe {
        /// Offending id.
        capability_id: String,
    },
}

/// Compute the PascalCase variant name for a snake_case capability id.
///
/// Rules:
/// - split on `_` and `.`
/// - capitalize each segment
/// - reject any character outside `[A-Za-z0-9]`
fn pascal_case(capability_id: &str) -> Result<String, CodegenError> {
    if !capability_id
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '.')
    {
        return Err(CodegenError::NonIdentifierSafe {
            capability_id: capability_id.to_string(),
        });
    }
    let mut out = String::with_capacity(capability_id.len());
    let mut capitalize_next = true;
    for c in capability_id.chars() {
        match c {
            '_' | '.' => {
                capitalize_next = true;
            }
            other if capitalize_next => {
                out.extend(other.to_uppercase());
                capitalize_next = false;
            }
            other => {
                out.push(other);
            }
        }
    }
    Ok(out)
}

/// Generate the Rust `enum CapabilityId` artifact.
///
/// Output is wrapped in a `pub mod generated` block so the codegen'd
/// `CapabilityId` enum (the closed enumeration) does not collide with the
/// string-wrapper `crate::registry::CapabilityId` (the dynamic lookup key).
/// Callers reach the generated enum at
/// `video_capabilities::generated::CapabilityId`.
pub fn render_rust_enum(document: &RegistryDocument) -> Result<String, CodegenError> {
    let mut sorted: Vec<&str> = document
        .capabilities
        .iter()
        .map(|c| c.capability_id.0.as_str())
        .collect();
    sorted.sort();
    sorted.dedup();

    let mut variants = Vec::with_capacity(sorted.len());
    let mut arms = Vec::with_capacity(sorted.len());
    let mut all_arms = Vec::with_capacity(sorted.len());
    for id in &sorted {
        let variant = pascal_case(id)?;
        variants.push(variant.clone());
        arms.push(format!("            Self::{variant} => \"{id}\","));
        all_arms.push(format!("            \"{id}\" => Ok(Self::{variant}),"));
    }

    let mut buf = String::new();
    writeln!(
        &mut buf,
        "// AUTO-GENERATED by codegen.rs from docs/dispatch/v2/source/capability-registry.json."
    )
    .unwrap();
    writeln!(
        &mut buf,
        "// DO NOT EDIT — re-run the codegen instead."
    )
    .unwrap();
    writeln!(&mut buf, "// Schema: {GENERATOR_SCHEMA}").unwrap();
    writeln!(&mut buf).unwrap();
    writeln!(&mut buf, "// Wrap the generated enum in a module so it does not").unwrap();
    writeln!(
        &mut buf,
        "// collide with `crate::registry::CapabilityId` (the dynamic lookup key)."
    )
    .unwrap();
    writeln!(&mut buf, "pub mod generated {{").unwrap();
    writeln!(&mut buf, "    #![allow(missing_docs)]").unwrap();
    writeln!(&mut buf).unwrap();
    writeln!(
        &mut buf,
        "/// Exhaustive list of capability ids declared by the canonical registry."
    )
    .unwrap();
    writeln!(
        &mut buf,
        "/// Generated by `video_capabilities::codegen` from the canonical"
    )
    .unwrap();
    writeln!(
        &mut buf,
        "/// registry; do not edit by hand."
    )
    .unwrap();
    writeln!(&mut buf, "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]").unwrap();
    writeln!(&mut buf, "pub enum CapabilityId {{").unwrap();
    for v in &variants {
        writeln!(&mut buf, "    {v},").unwrap();
    }
    writeln!(&mut buf, "}}").unwrap();
    writeln!(&mut buf).unwrap();
    writeln!(
        &mut buf,
        "impl CapabilityId {{"
    )
    .unwrap();
    writeln!(
        &mut buf,
        "    /// Stable snake_case id as it appears in the registry."
    )
    .unwrap();
    writeln!(
        &mut buf,
        "    pub fn as_str(self) -> &'static str {{"
    )
    .unwrap();
    writeln!(&mut buf, "        match self {{").unwrap();
    for line in &arms {
        writeln!(&mut buf, "{line}").unwrap();
    }
    writeln!(&mut buf, "        }}").unwrap();
    writeln!(&mut buf, "    }}").unwrap();
    writeln!(&mut buf).unwrap();
    writeln!(
        &mut buf,
        "    /// Try to parse a snake_case id back into the enum."
    )
    .unwrap();
    writeln!(
        &mut buf,
        "    pub fn from_str_strict(value: &str) -> Result<Self, String> {{"
    )
    .unwrap();
    writeln!(&mut buf, "        match value {{").unwrap();
    for line in &all_arms {
        writeln!(&mut buf, "{line}").unwrap();
    }
    writeln!(
        &mut buf,
        "            other => Err(format!(\"unknown capability id: {{}}\", other)),"
    )
    .unwrap();
    writeln!(&mut buf, "        }}").unwrap();
    writeln!(&mut buf, "    }}").unwrap();
    writeln!(
        &mut buf,
        "    /// All known capability ids, in stable (sorted) order."
    )
    .unwrap();
    writeln!(
        &mut buf,
        "    pub const ALL: &'static [CapabilityId] = &["
    )
    .unwrap();
    for v in &variants {
        writeln!(&mut buf, "        Self::{v},").unwrap();
    }
    writeln!(&mut buf, "    ];").unwrap();
    writeln!(&mut buf, "}}").unwrap();
    writeln!(&mut buf, "}}").unwrap();
    writeln!(&mut buf).unwrap();

    Ok(buf)
}

/// Generate the TypeScript `capabilities.ts` artifact.
pub fn render_typescript(document: &RegistryDocument) -> Result<String, CodegenError> {
    let mut sorted: Vec<&crate::registry::Capability> =
        document.capabilities.iter().collect();
    sorted.sort_by(|a, b| a.capability_id.0.cmp(&b.capability_id.0));

    let mut buf = String::new();
    writeln!(
        &mut buf,
        "// AUTO-GENERATED by codegen.rs from docs/dispatch/v2/source/capability-registry.json."
    )
    .unwrap();
    writeln!(
        &mut buf,
        "// DO NOT EDIT — re-run the codegen instead."
    )
    .unwrap();
    writeln!(&mut buf, "// Schema: {GENERATOR_SCHEMA}").unwrap();
    writeln!(&mut buf).unwrap();
    writeln!(
        &mut buf,
        "export type CapabilityKind = 'read' | 'mutation';"
    )
    .unwrap();
    writeln!(
        &mut buf,
        "export type Degradation = 'ok' | 'degraded' | 'missing';"
    )
    .unwrap();
    writeln!(&mut buf).unwrap();
    writeln!(
        &mut buf,
        "export interface CapabilityDescriptor {{"
    )
    .unwrap();
    writeln!(&mut buf, "  readonly id: string;").unwrap();
    writeln!(&mut buf, "  readonly version: number;").unwrap();
    writeln!(&mut buf, "  readonly kind: CapabilityKind;").unwrap();
    writeln!(&mut buf, "  readonly ownerComponent: string;").unwrap();
    writeln!(&mut buf, "  readonly permissionSet: string;").unwrap();
    writeln!(
        &mut buf,
        "  readonly outputs: {{ readonly bounded: boolean; readonly windowed: boolean; readonly maxItems?: number }};"
    )
    .unwrap();
    writeln!(
        &mut buf,
        "  readonly degradation: Degradation;"
    )
    .unwrap();
    writeln!(&mut buf, "}}").unwrap();
    writeln!(&mut buf).unwrap();

    writeln!(
        &mut buf,
        "export const CAPABILITY_DESCRIPTORS: ReadonlyArray<CapabilityDescriptor> = ["
    )
    .unwrap();
    for cap in &sorted {
        let kind = match cap.kind {
            CapabilityKind::Read => "read",
            CapabilityKind::Mutation => "mutation",
        };
        let degradation = cap
            .degradation
            .map(|d| match d {
                crate::registry::Degradation::Ok => "ok",
                crate::registry::Degradation::Degraded => "degraded",
                crate::registry::Degradation::Missing => "missing",
            })
            .unwrap_or("ok");
        let max_items = cap
            .outputs
            .max_items
            .map(|m| format!(", maxItems: {m}"))
            .unwrap_or_default();
        writeln!(
            &mut buf,
            "  {{ id: '{id}', version: {ver}, kind: '{kind}', ownerComponent: '{owner}', permissionSet: '{pset}', outputs: {{ bounded: {bounded}, windowed: {windowed}{max_items} }}, degradation: '{deg}' }},",
            id = cap.capability_id.0,
            ver = cap.version,
            owner = cap.owner_component,
            pset = cap.permission_set,
            bounded = cap.outputs.bounded,
            windowed = cap.outputs.windowed,
            deg = degradation,
        )
        .unwrap();
    }
    writeln!(&mut buf, "];").unwrap();
    writeln!(&mut buf).unwrap();

    let ids: BTreeSet<&str> = sorted.iter().map(|c| c.capability_id.0.as_str()).collect();
    writeln!(
        &mut buf,
        "export const CAPABILITY_IDS: ReadonlyArray<string> = ["
    )
    .unwrap();
    for id in &ids {
        writeln!(&mut buf, "  '{id}',").unwrap();
    }
    writeln!(&mut buf, "];").unwrap();
    writeln!(&mut buf).unwrap();

    writeln!(
        &mut buf,
        "export function isKnownCapabilityId(value: string): boolean {{"
    )
    .unwrap();
    writeln!(&mut buf, "  return (CAPABILITY_IDS as ReadonlyArray<string>).includes(value);").unwrap();
    writeln!(&mut buf, "}}").unwrap();
    Ok(buf)
}

/// Generate the JSON tool registry stub consumed by the loopback MCP adapter
/// in B2-025. Output is byte-stable because we serialize via `serde_json` with
/// BTreeMap keys (sorted).
pub fn render_mcp_tool_registry(document: &RegistryDocument) -> Result<String, CodegenError> {
    let mut sorted: Vec<&crate::registry::Capability> =
        document.capabilities.iter().collect();
    sorted.sort_by(|a, b| a.capability_id.0.cmp(&b.capability_id.0));

    let mut tools = serde_json::Map::new();
    for cap in &sorted {
        let entry = serde_json::json!({
            "schema": "cutright.mcp_tool/v1",
            "capability_id": cap.capability_id.0,
            "kind": match cap.kind {
                CapabilityKind::Read => "read",
                CapabilityKind::Mutation => "mutation",
            },
            "owner_component": cap.owner_component,
            "permission_set": cap.permission_set,
            "description": format!(
                "{} capability generated from the canonical registry (CR-V2-B2-014).",
                match cap.kind {
                    CapabilityKind::Read => "Read",
                    CapabilityKind::Mutation => "Mutation",
                }
            ),
            "input_schema": cap.inputs,
        });
        tools.insert(cap.capability_id.0.clone(), entry);
    }
    let value = serde_json::json!({
        "schema": "cutright.mcp_tool_registry/v1",
        "registry_id": document.registry_id,
        "generator": GENERATOR_SCHEMA,
        "tools": tools,
    });
    serde_json::to_string_pretty(&value).map_err(|e| CodegenError::Io {
        path: PathBuf::from("<mcp-tool-registry>"),
        source: std::io::Error::new(std::io::ErrorKind::Other, e),
    })
}

/// Write an artifact to disk atomically (temp-file + rename) and report what
/// was written.
pub fn write_artifact(path: &Path, contents: &str) -> Result<(), CodegenError> {
    use std::io::Write as _;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|source| CodegenError::Io {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    let tmp = path.with_extension("tmp");
    {
        let mut file = std::fs::File::create(&tmp).map_err(|source| CodegenError::Io {
            path: tmp.clone(),
            source,
        })?;
        file.write_all(contents.as_bytes())
            .map_err(|source| CodegenError::Io {
                path: tmp.clone(),
                source,
            })?;
        file.sync_all().map_err(|source| CodegenError::Io {
            path: tmp.clone(),
            source,
        })?;
    }
    std::fs::rename(&tmp, path).map_err(|source| CodegenError::Io {
        path: path.to_path_buf(),
        source,
    })?;
    Ok(())
}

/// Run the full codegen pipeline against a registry document and write every
/// artifact in place. The returned list reports what was written and how many
/// bytes each artifact contains.
pub fn generate_all(
    document: &RegistryDocument,
    out_rust: &Path,
    out_ts: &Path,
    out_mcp: &Path,
) -> Result<Vec<(&'static str, usize)>, CodegenError> {
    let rust = render_rust_enum(document)?;
    write_artifact(out_rust, &rust)?;
    let ts = render_typescript(document)?;
    write_artifact(out_ts, &ts)?;
    let mcp = render_mcp_tool_registry(document)?;
    write_artifact(out_mcp, &mcp)?;
    Ok(vec![
        ("rust", rust.len()),
        ("typescript", ts.len()),
        ("mcp_tool_registry", mcp.len()),
    ])
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::permission::{PermissionGrant, PermissionSet, Scope, PERMISSION_SET_SCHEMA};
    use crate::registry::{
        Capability, CapabilityId, CapabilityKind, CapabilityOutputs, Degradation,
        RegistryDocument, REGISTRY_SCHEMA, REGISTRY_SCHEMA_VERSION,
    };

    fn sample_document() -> RegistryDocument {
        let cap = |id: &str, kind: CapabilityKind| Capability {
            schema: REGISTRY_SCHEMA.into(),
            capability_id: CapabilityId::new(id),
            version: 1,
            kind,
            owner_component: "video-project".into(),
            permission_set: "pset.basic".into(),
            inputs: serde_json::json!({}),
            outputs: CapabilityOutputs::default(),
            eval_suites: vec![],
            degradation: Some(Degradation::Ok),
        };
        RegistryDocument {
            schema_version: REGISTRY_SCHEMA_VERSION,
            registry_id: "cutright-v2-test".into(),
            note: None,
            capabilities: vec![
                cap("timeline.read", CapabilityKind::Read),
                cap("timeline.cut", CapabilityKind::Mutation),
            ],
            permission_sets: vec![PermissionSet {
                schema: PERMISSION_SET_SCHEMA.into(),
                permission_set_id: "pset.basic".into(),
                grants: vec![PermissionGrant {
                    capability: "timeline.read".into(),
                    scope: Scope::TimelineRead,
                }],
            }],
        }
    }

    #[test]
    fn pascal_case_handles_snake_and_dot_segments() {
        assert_eq!(pascal_case("timeline.read").unwrap(), "TimelineRead");
        assert_eq!(
            pascal_case("evidence.read_contracts").unwrap(),
            "EvidenceReadContracts"
        );
        assert_eq!(pascal_case("pack.manage").unwrap(), "PackManage");
    }

    #[test]
    fn pascal_case_rejects_unsafe_characters() {
        let err = pascal_case("hello/world").unwrap_err();
        let msg = format!("{err}");
        assert!(msg.contains("non-identifier"));
    }

    #[test]
    fn rust_enum_is_byte_stable() {
        let doc = sample_document();
        let a = render_rust_enum(&doc).unwrap();
        let b = render_rust_enum(&doc).unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn rust_enum_contains_expected_variants() {
        let doc = sample_document();
        let code = render_rust_enum(&doc).unwrap();
        assert!(code.contains("pub enum CapabilityId"));
        assert!(code.contains("    TimelineRead,"));
        assert!(code.contains("    TimelineCut,"));
        assert!(code.contains("Self::TimelineRead => \"timeline.read\""));
    }

    #[test]
    fn typescript_is_byte_stable() {
        let doc = sample_document();
        let a = render_typescript(&doc).unwrap();
        let b = render_typescript(&doc).unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn mcp_tool_registry_is_byte_stable() {
        let doc = sample_document();
        let a = render_mcp_tool_registry(&doc).unwrap();
        let b = render_mcp_tool_registry(&doc).unwrap();
        assert_eq!(a, b);
        let value: serde_json::Value = serde_json::from_str(&a).unwrap();
        assert_eq!(value["schema"], "cutright.mcp_tool_registry/v1");
        assert!(value["tools"]["timeline.read"].is_object());
        assert!(value["tools"]["timeline.cut"].is_object());
    }
}
