//! Capability registry documentation generator (CR-V2-B2-016).
//!
//! Renders the canonical capability registry as a single Markdown document
//! at `docs/dispatch/v2/book-2/capabilities.md`. The output is byte-stable:
//! capabilities are listed in sorted order, permission sets are referenced
//! by id, and every block of prose is identical between runs.
//!
//! The generator is intentionally narrow — it does NOT try to be a full
//! docs site. Its job is to keep the human-facing catalogue in lockstep
//! with the canonical JSON so reviewers can audit the registry without
//! touching the source file.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use crate::registry::{Capability, CapabilityKind, RegistryDocument};

/// Schema id embedded in the generated markdown front matter.
pub const DOCS_SCHEMA: &str = "cutright.capability_docs/v1";

/// Render the documentation page as a Markdown string. Pure function: same
/// registry in, same bytes out.
pub fn render_markdown(document: &RegistryDocument) -> String {
    let mut buf = String::new();
    writeln!(&mut buf, "<!--").unwrap();
    writeln!(&mut buf, " AUTO-GENERATED by video-capabilities::docs.").unwrap();
    writeln!(
        &mut buf,
        " DO NOT EDIT — re-run the docs generator instead."
    )
    .unwrap();
    writeln!(&mut buf, " Schema: {DOCS_SCHEMA}").unwrap();
    writeln!(&mut buf, "-->\n").unwrap();

    writeln!(&mut buf, "# Book 2 — Canonical Capability Registry\n").unwrap();
    writeln!(
        &mut buf,
        "Generated from `{}` (registry id `{}`).",
        document.registry_id, document.registry_id
    )
    .unwrap();
    writeln!(
        &mut buf,
        "Capabilities are the unit of authorisation surfaced to the Studio, \
         the JSON CLI, and the loopback MCP adapter. Every action batch is \
         validated against this registry before it reaches the executor.\n"
    )
    .unwrap();

    writeln!(&mut buf, "## Summary\n").unwrap();
    let mut caps: Vec<&Capability> = document.capabilities.iter().collect();
    caps.sort_by(|a, b| a.capability_id.0.cmp(&b.capability_id.0));
    let read_count = caps
        .iter()
        .filter(|c| matches!(c.kind, CapabilityKind::Read))
        .count();
    let mutation_count = caps
        .iter()
        .filter(|c| matches!(c.kind, CapabilityKind::Mutation))
        .count();
    writeln!(
        &mut buf,
        "| capability | kind | version | owner | permission set | bounded | windowed |\n\
         |---|---|---|---|---|---|---|"
    )
    .unwrap();
    for cap in &caps {
        writeln!(
            &mut buf,
            "| `{}` | {:?} | {} | `{}` | `{}` | {} | {} |",
            cap.capability_id.0,
            cap.kind,
            cap.version,
            cap.owner_component,
            cap.permission_set,
            cap.outputs.bounded,
            cap.outputs.windowed
        )
        .unwrap();
    }
    writeln!(
        &mut buf,
        "\nTotals: {} read, {} mutation, {} capabilities.\n",
        read_count,
        mutation_count,
        caps.len()
    )
    .unwrap();

    writeln!(&mut buf, "## Permission sets\n").unwrap();
    let mut psets: Vec<&_> = document.permission_sets.iter().collect();
    psets.sort_by(|a, b| a.permission_set_id.cmp(&b.permission_set_id));
    for pset in psets {
        writeln!(
            &mut buf,
            "### `{}` (schema `{}`)",
            pset.permission_set_id, pset.schema
        )
        .unwrap();
        writeln!(&mut buf, "\nGrants:\n").unwrap();
        writeln!(&mut buf, "| capability | scope |\n|---|---|").unwrap();
        let mut grants: Vec<_> = pset.grants.iter().collect();
        grants.sort_by(|a, b| {
            a.capability
                .cmp(&b.capability)
                .then_with(|| format!("{:?}", a.scope).cmp(&format!("{:?}", b.scope)))
        });
        for grant in grants {
            writeln!(&mut buf, "| `{}` | `{:?}` |", grant.capability, grant.scope).unwrap();
        }
        writeln!(&mut buf).unwrap();
    }

    writeln!(&mut buf, "## Capability detail\n").unwrap();
    for cap in &caps {
        writeln!(&mut buf, "### `{}`\n", cap.capability_id.0).unwrap();
        writeln!(
            &mut buf,
            "- Schema: `{}`\n- Version: {}\n- Kind: `{:?}`\n- Owner component: `{}`\n- Permission set: `{}`",
            cap.schema, cap.version, cap.kind, cap.owner_component, cap.permission_set
        )
        .unwrap();
        writeln!(
            &mut buf,
            "- Outputs: bounded={}, windowed={}, max_items={}",
            cap.outputs.bounded,
            cap.outputs.windowed,
            cap.outputs
                .max_items
                .map(|m| m.to_string())
                .unwrap_or_else(|| "—".to_string())
        )
        .unwrap();
        writeln!(
            &mut buf,
            "- Degradation: `{}`",
            cap.degradation
                .map(|d| format!("{d:?}"))
                .unwrap_or_else(|| "ok".to_string())
        )
        .unwrap();
        if !cap.eval_suites.is_empty() {
            writeln!(&mut buf, "- Eval suites:").unwrap();
            for suite in &cap.eval_suites {
                writeln!(&mut buf, "  - `{suite}`").unwrap();
            }
        }
        writeln!(&mut buf).unwrap();
    }

    buf
}

/// Write the rendered documentation to disk and return the byte count.
pub fn write_markdown(document: &RegistryDocument, out: &Path) -> Result<usize, std::io::Error> {
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent)?;
    }
    let bytes = render_markdown(document);
    fs::write(out, &bytes)?;
    Ok(bytes.len())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::permission::{PermissionGrant, PermissionSet, Scope};
    use crate::registry::{
        Capability, CapabilityId, CapabilityKind, CapabilityOutputs, Degradation,
    };

    fn sample_doc() -> RegistryDocument {
        RegistryDocument {
            schema_version: 1,
            registry_id: "test".into(),
            note: None,
            capabilities: vec![Capability {
                schema: "cutright.capability/v1".into(),
                capability_id: CapabilityId::new("timeline.read"),
                version: 1,
                kind: CapabilityKind::Read,
                owner_component: "video-state".into(),
                permission_set: "pset.read_only".into(),
                inputs: serde_json::json!({}),
                outputs: CapabilityOutputs {
                    bounded: true,
                    windowed: true,
                    max_items: Some(100),
                },
                eval_suites: vec!["eval.timeline_read_contracts".into()],
                degradation: Some(Degradation::Ok),
            }],
            permission_sets: vec![PermissionSet {
                schema: "cutright.permission_set/v1".into(),
                permission_set_id: "pset.read_only".into(),
                grants: vec![PermissionGrant {
                    capability: "timeline.read".into(),
                    scope: Scope::TimelineRead,
                }],
            }],
        }
    }

    #[test]
    fn render_markdown_is_byte_stable() {
        let a = render_markdown(&sample_doc());
        let b = render_markdown(&sample_doc());
        assert_eq!(a, b);
    }

    #[test]
    fn render_markdown_includes_every_capability() {
        let doc = sample_doc();
        let md = render_markdown(&doc);
        assert!(md.contains("`timeline.read`"));
        assert!(md.contains("`pset.read_only`"));
        assert!(md.contains("eval.timeline_read_contracts"));
    }
}
