// AUTO-GENERATED by codegen.rs from docs/dispatch/v2/source/capability-registry.json.
// DO NOT EDIT — re-run the codegen instead.
// Schema: cutright.capability_codegen/v1

// Wrap the generated enum in a module so it does not
// collide with `crate::registry::CapabilityId` (the dynamic lookup key).
pub mod generated {
    #![allow(missing_docs)]

/// Exhaustive list of capability ids declared by the canonical registry.
/// Generated by `video_capabilities::codegen` from the canonical
/// registry; do not edit by hand.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum CapabilityId {
    AssetPlan,
    EvidenceRead,
    ExportPublish,
    PackManage,
    RenderDispatch,
    SettingsWrite,
    TimelineCut,
    TimelineRead,
}

impl CapabilityId {
    /// Stable snake_case id as it appears in the registry.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::AssetPlan => "asset.plan",
            Self::EvidenceRead => "evidence.read",
            Self::ExportPublish => "export.publish",
            Self::PackManage => "pack.manage",
            Self::RenderDispatch => "render.dispatch",
            Self::SettingsWrite => "settings.write",
            Self::TimelineCut => "timeline.cut",
            Self::TimelineRead => "timeline.read",
        }
    }

    /// Try to parse a snake_case id back into the enum.
    pub fn from_str_strict(value: &str) -> Result<Self, String> {
        match value {
            "asset.plan" => Ok(Self::AssetPlan),
            "evidence.read" => Ok(Self::EvidenceRead),
            "export.publish" => Ok(Self::ExportPublish),
            "pack.manage" => Ok(Self::PackManage),
            "render.dispatch" => Ok(Self::RenderDispatch),
            "settings.write" => Ok(Self::SettingsWrite),
            "timeline.cut" => Ok(Self::TimelineCut),
            "timeline.read" => Ok(Self::TimelineRead),
            other => Err(format!("unknown capability id: {}", other)),
        }
    }
    /// All known capability ids, in stable (sorted) order.
    pub const ALL: &'static [CapabilityId] = &[
        Self::AssetPlan,
        Self::EvidenceRead,
        Self::ExportPublish,
        Self::PackManage,
        Self::RenderDispatch,
        Self::SettingsWrite,
        Self::TimelineCut,
        Self::TimelineRead,
    ];
}
}

