// AUTO-GENERATED by codegen.rs from docs/dispatch/v2/source/capability-registry.json.
// DO NOT EDIT — re-run the codegen instead.
// Schema: cutright.capability_codegen/v1

export type CapabilityKind = 'read' | 'mutation';
export type Degradation = 'ok' | 'degraded' | 'missing';

export interface CapabilityDescriptor {
  readonly id: string;
  readonly version: number;
  readonly kind: CapabilityKind;
  readonly ownerComponent: string;
  readonly permissionSet: string;
  readonly outputs: { readonly bounded: boolean; readonly windowed: boolean; readonly maxItems?: number };
  readonly degradation: Degradation;
}

export const CAPABILITY_DESCRIPTORS: ReadonlyArray<CapabilityDescriptor> = [
  { id: 'asset.plan', version: 1, kind: 'mutation', ownerComponent: 'video-actions', permissionSet: 'pset.asset_plan', outputs: { bounded: false, windowed: false }, degradation: 'ok' },
  { id: 'evidence.read', version: 1, kind: 'read', ownerComponent: 'video-state', permissionSet: 'pset.evidence_read_only', outputs: { bounded: true, windowed: true, maxItems: 10000 }, degradation: 'ok' },
  { id: 'export.publish', version: 1, kind: 'mutation', ownerComponent: 'video-jobs', permissionSet: 'pset.render_jobs', outputs: { bounded: false, windowed: false }, degradation: 'ok' },
  { id: 'pack.manage', version: 1, kind: 'mutation', ownerComponent: 'video-runtime', permissionSet: 'pset.pack_manager', outputs: { bounded: false, windowed: false }, degradation: 'ok' },
  { id: 'render.dispatch', version: 1, kind: 'mutation', ownerComponent: 'video-jobs', permissionSet: 'pset.render_jobs', outputs: { bounded: false, windowed: false }, degradation: 'ok' },
  { id: 'settings.write', version: 1, kind: 'mutation', ownerComponent: 'video-project', permissionSet: 'pset.pack_manager', outputs: { bounded: false, windowed: false }, degradation: 'ok' },
  { id: 'timeline.cut', version: 1, kind: 'mutation', ownerComponent: 'video-actions', permissionSet: 'pset.editorial_engine', outputs: { bounded: false, windowed: false }, degradation: 'ok' },
  { id: 'timeline.read', version: 1, kind: 'read', ownerComponent: 'video-state', permissionSet: 'pset.evidence_read_only', outputs: { bounded: true, windowed: true }, degradation: 'ok' },
];

export const CAPABILITY_IDS: ReadonlyArray<string> = [
  'asset.plan',
  'evidence.read',
  'export.publish',
  'pack.manage',
  'render.dispatch',
  'settings.write',
  'timeline.cut',
  'timeline.read',
];

export function isKnownCapabilityId(value: string): boolean {
  return (CAPABILITY_IDS as ReadonlyArray<string>).includes(value);
}
