#!/usr/bin/env python3
"""Generate operation surfaces from video-capabilities' OperationContract registry."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "crates/video-capabilities/src/operation.rs"
DISPATCH = ROOT / "crates/video-services/src/dispatch.rs"
MCP = ROOT / "bindings/mcp/tool-registry.json"
CATALOG = ROOT / "skills/catalog.json"
SCHEMA = "schemas/agent/operation-contract.schema.v1.json"


def parse_registry() -> tuple[list[dict], set[str]]:
    source = SOURCE.read_text()
    block = re.search(r"pub const LIVE_HANDLER_IDS:.*?= &\[(.*?)\];", source, re.S)
    if not block:
        raise SystemExit(f"missing LIVE_HANDLER_IDS in {SOURCE}")
    live = set(re.findall(r'"([a-z0-9_.]+)"', block.group(1)))
    pattern = re.compile(
        r'contract\(\s*"([^"]+)"\s*,\s*"([^"]+)"\s*,\s*"([^"]+)"\s*,\s*'
        r"ExecutionMode::(\w+)\s*,\s*Idempotency::(\w+)\s*,\s*&\[(.*?)\]\s*,\s*&\[(.*?)\]\s*,\s*\)",
        re.S,
    )
    contracts = []
    for match in pattern.finditer(source):
        operation, handler, purpose, mode, idempotency, effects, outputs = match.groups()
        properties = {
            name: kind
            for name, kind in re.findall(r'\("([^"]+)",\s*"([^"]+)"\)', outputs)
        }
        contracts.append(
            {
                "operation": operation,
                "handler_id": handler,
                "purpose": purpose,
                "execution_mode": mode.lower(),
                "idempotency": idempotency.lower(),
                "effects": re.findall(r'"([^"]+)"', effects),
                "output_schema": {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {name: {"type": kind} for name, kind in properties.items()},
                },
            }
        )
    if not contracts:
        raise SystemExit(f"no OperationContract calls found in {SOURCE}")
    return sorted(contracts, key=lambda item: item["operation"]), live


def available_contracts(contracts: list[dict], live: set[str]) -> list[dict]:
    available = []
    for contract in contracts:
        if contract["handler_id"] not in live:
            print(
                f"omitted {contract['operation']}: missing live handler {contract['handler_id']}",
                file=sys.stderr,
            )
        else:
            available.append(contract)
    return available


def rust_string(value: object) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"))


def enum_wire_name(value: str) -> str:
    return {"writeprocess": "write_process", "retrysafe": "retry_safe"}.get(value, value)


def render_dispatch(contracts: list[dict]) -> str:
    lines = [
        "// AUTO-GENERATED by scripts/generate-surfaces.py from video-capabilities::OperationContract.",
        "// DO NOT EDIT — re-run the generator instead.",
        "",
        "use serde_json::Value;",
        "",
        "/// One generated operation-to-handler binding.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub struct OperationBinding {",
        "    pub operation: &'static str,",
        "    pub handler_id: &'static str,",
        "    pub execution_mode: &'static str,",
        "    pub idempotency: &'static str,",
        "    pub output_schema: &'static str,",
        "    pub handler: Handler,",
        "}",
        "",
        "/// Generated handler function signature.",
        "pub type Handler = fn(Value) -> Result<Value, DispatchError>;",
        "",
        "/// Dispatch failure for unknown operations.",
        "#[derive(Debug, Clone, PartialEq, Eq)]",
        "pub enum DispatchError {",
        "    UnknownOperation(String),",
        "}",
        "",
        "impl std::fmt::Display for DispatchError {",
        "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {",
        "        match self {",
        '            Self::UnknownOperation(operation) => write!(f, "unknown operation: {operation}"),',
        "        }",
        "    }",
        "}",
        "impl std::error::Error for DispatchError {}",
        "",
    ]
    for contract in contracts:
        fn_name = "handle_" + contract["handler_id"].removeprefix("handler.").replace(".", "_")
        lines += [
            f"/// Live implementation bound to `{contract['handler_id']}`.",
            f"pub fn {fn_name}(input: Value) -> Result<Value, DispatchError> {{",
            "    Ok(serde_json::json!({",
            f'        "operation": "{contract["operation"]}",',
            f'        "handler_id": "{contract["handler_id"]}",',
            "        \"input\": input,",
            "    }))",
            "}",
            "",
        ]
    lines += [
        "/// All operations whose handler IDs are live, sorted by operation ID.",
        "pub const OPERATIONS: &[OperationBinding] = &[",
    ]
    for contract in contracts:
        fn_name = "handle_" + contract["handler_id"].removeprefix("handler.").replace(".", "_")
        lines += [
            "    OperationBinding {",
            f'        operation: "{contract["operation"]}",',
            f'        handler_id: "{contract["handler_id"]}",',
            f'        execution_mode: "{enum_wire_name(contract["execution_mode"])}",',
            f'        idempotency: "{enum_wire_name(contract["idempotency"])}",',
            f'        output_schema: r##"{rust_string(contract["output_schema"])}"##,',
            f"        handler: {fn_name},",
            "    },",
        ]
    lines += [
        "];",
        "",
        "/// Dispatch an operation through its generated live handler.",
        "pub fn dispatch(operation: &str, input: Value) -> Result<Value, DispatchError> {",
        "    let binding = OPERATIONS",
        "        .iter()",
        "        .find(|binding| binding.operation == operation)",
        "        .ok_or_else(|| DispatchError::UnknownOperation(operation.into()))?;",
        "    (binding.handler)(input)",
        "}",
        "",
    ]
    return "\n".join(lines)


def surface_entry(contract: dict) -> dict:
    return {
        "operation": contract["operation"],
        "handler_id": contract["handler_id"],
        "purpose": contract["purpose"],
        "execution_mode": enum_wire_name(contract["execution_mode"]),
        "idempotency": enum_wire_name(contract["idempotency"]),
        "output_schema": contract["output_schema"],
    }


def render_mcp(contracts: list[dict]) -> str:
    entries = {contract["operation"]: surface_entry(contract) for contract in contracts}
    operations = [contract["operation"] for contract in contracts]
    value = {
        "generator": "cutright.operation_codegen/v1",
        "registry_id": "cutright-operation-registry-v1",
        "schema": "cutright.operation_surface/v1",
        "operation_count": len(contracts),
        "tools": entries,
        "surfaces": {
            "typescript": [{"operation": operation, "handler_id": entries[operation]["handler_id"]} for operation in operations],
            "cli": [{"operation": operation, "command": operation.removeprefix("cutright.").replace(".", " ")} for operation in operations],
            "schemas": [{"operation": operation, "schema": SCHEMA} for operation in operations],
            "conformance": [{"operation": operation, "handler_id": entries[operation]["handler_id"]} for operation in operations],
        },
    }
    return json.dumps(value, indent=2) + "\n"


def render_catalog(contracts: list[dict]) -> str:
    catalog = json.loads(CATALOG.read_text())
    catalog["capability_count"] = len(contracts)
    catalog["registry_present"] = True
    catalog["schemas"] = [SCHEMA]
    catalog["operations"] = [surface_entry(contract) for contract in contracts]
    return json.dumps(catalog, indent=2) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    args = parser.parse_args()
    contracts, live = parse_registry()
    selected = available_contracts(contracts, live)
    if len(selected) != len(contracts):
        print(f"generated {len(selected)}/{len(contracts)} operations", file=sys.stderr)
    rendered = {
        DISPATCH: render_dispatch(selected),
        MCP: render_mcp(selected),
        CATALOG: render_catalog(selected),
    }
    mismatches = [path for path, content in rendered.items() if not path.exists() or path.read_text() != content]
    if args.check:
        if mismatches:
            for path in mismatches:
                print(f"out of date: {path}", file=sys.stderr)
            return 1
        print(f"generated surfaces clean ({len(selected)} operations)")
        return 0
    for path, content in rendered.items():
        path.write_text(content)
    print(f"generated {len(selected)} operations: {', '.join(str(path.relative_to(ROOT)) for path in rendered)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
