#!/usr/bin/env bash
#
# scripts/resolve-license.sh — CutRight third-party asset license gate
# (hardening plan §7.3: license/asset resolution).
#
# Scans the repository for third-party media / font / asset files and asserts
# that each one carries a license note. This is a conservative inventory gate:
# it NEVER fabricates a license. An asset passes only when one of these holds:
#
#   1. Manifest note — a license manifest (LICENSES.md, LICENSE.md, LICENSE,
#      or a LICENSES/ directory of *.md / *.txt files) exists in the asset's
#      own directory or any ancestor up to the repo root, AND that manifest
#      names the asset. Matching uses a normalized form of the file's basename
#      (lowercased, non-alphanumerics stripped), so "geist-variable.woff2"
#      matches a "## Geist Variable" heading and "tanker-regular.woff2"
#      matches "## Tanker Regular".
#   2. Sidecar note — a license file sits next to the asset, e.g.
#      "<name>.license", "<name>.LICENSE", "<name>.LICENSE.md".
#   3. First-party declaration — the asset's repo-relative path is listed in
#      scripts/license-allowlist.txt. This is for assets authored in-house
#      (e.g. the app icon) or generated by our own pipeline (doc renders),
#      which need no third-party license. Declaring provenance here is an
#      explicit owner assertion, not a fabricated upstream license.
#
# Any asset that is not covered is reported, and the script exits non-zero.
#
# Generated / vendored / build / VCS directories are pruned from the scan
# (node_modules, cargo target/, vite dist/, Tauri gen/, QA caches, python
# venvs, tool/audit state, VCS metadata). They are not shipped source assets
# and would only add noise. See PRUNE_DIRS below.
#
# Portable across macOS (bash 3.2) and Linux. Repo root is resolved from this
# script's own location.

set -euo pipefail

SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd -P "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

ALLOWLIST="scripts/license-allowlist.txt"

# Asset extensions treated as third-party media/font/asset candidates.
ASSET_RE='\.(ttf|otf|woff|woff2|png|jpe?g|gif|svg|webp|ico|bmp|mp4|mov|webm|wav|mp3|aac|flac|ogg|m4a)$'

# Directory basenames pruned from the scan (generated / vendored / build / VCS).
PRUNE_DIRS=".git .github node_modules target dist gen .cache .cutright-tools .audit .tether"

# normalize <string>: lowercase and strip everything that is not a-z0-9.
normalize() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9'
}

# is_allowlisted <repo-relative-path>: exact path listed in the allowlist
# (comments and blank lines ignored, surrounding whitespace trimmed).
is_allowlisted() {
  local rel="$1"
  [ -f "$ALLOWLIST" ] || return 1
  grep -vE '^[[:space:]]*(#|$)' "$ALLOWLIST" \
    | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
    | grep -Fxq "$rel"
}

# manifest_matches <manifest-file> <token>: true if the normalized manifest
# text contains the normalized asset token.
manifest_matches() {
  local hay
  hay="$(normalize "$(cat "$1")")"
  case "$hay" in
    *"$2"*) return 0 ;;
    *) return 1 ;;
  esac
}

# manifest_covers <repo-relative-path> <token>: walk from the asset's directory
# up to the repo root; true if any license manifest found along the way names
# the asset.
manifest_covers() {
  local rel="$1" token="$2"
  local dir m f
  dir="$(dirname "$rel")"
  while :; do
    for m in "$dir/LICENSES.md" "$dir/LICENSE.md" "$dir/LICENSE"; do
      if [ -f "$m" ] && manifest_matches "$m" "$token"; then
        return 0
      fi
    done
    if [ -d "$dir/LICENSES" ]; then
      while IFS= read -r f; do
        if manifest_matches "$f" "$token"; then
          return 0
        fi
      done <<EOF
$(find "$dir/LICENSES" -type f \( -name '*.md' -o -name '*.txt' \))
EOF
    fi
    [ "$dir" = "." ] && break
    dir="$(dirname "$dir")"
  done
  return 1
}

# has_sidecar <repo-relative-path>: true if a sidecar license file exists.
has_sidecar() {
  local rel="$1"
  local base stem dir ext
  base="${rel##*/}"
  stem="${base%.*}"
  dir="$(dirname "$rel")"
  for ext in license LICENSE LICENSE.md license.txt LICENSE.txt; do
    [ -f "$dir/$stem.$ext" ] && return 0
  done
  return 1
}

# --- collect candidate assets ------------------------------------------------
# Build the find prune expression: ( -name X -o -name Y ... ) -prune
prune_expr=""
for d in $PRUNE_DIRS; do
  prune_expr="$prune_expr -o -name $d"
done
prune_expr="${prune_expr# -o }"

# `|| true` keeps an empty result from tripping pipefail/set -e.
assets="$(
  eval "find \"\$ROOT\" \\( $prune_expr -o -name '.venv*' \\) -prune -o -type f -print" \
    | { grep -Ei "$ASSET_RE" || true; } \
    | sort
)"

# --- evaluate coverage -------------------------------------------------------
unlicensed=""
unlicensed_count=0
checked=0

while IFS= read -r abs; do
  [ -n "$abs" ] || continue
  rel="${abs#"$ROOT"/}"
  checked=$((checked + 1))

  base="${rel##*/}"
  stem="${base%.*}"
  token="$(normalize "$stem")"

  if is_allowlisted "$rel"; then
    continue
  fi
  if [ -n "$token" ] && manifest_covers "$rel" "$token"; then
    continue
  fi
  if has_sidecar "$rel"; then
    continue
  fi

  unlicensed="$unlicensed  - $rel
"
  unlicensed_count=$((unlicensed_count + 1))
done <<EOF
$assets
EOF

echo "resolve-license: repo root = $ROOT"
echo "resolve-license: scanned $checked asset file(s) (generated/vendored dirs pruned)."

if [ "$unlicensed_count" -gt 0 ]; then
  {
    echo "resolve-license: FAIL — $unlicensed_count asset(s) without a license note:"
    printf '%s' "$unlicensed"
    cat <<'EOF'

Each third-party asset needs a license note. Fix one of these ways:
  * add the asset to a LICENSES.md manifest in its directory (a heading or line
    naming the asset, plus its source and license), or
  * add a sidecar "<name>.license" file next to the asset, or
  * if it is first-party / generated in-house, declare its repo-relative path
    in scripts/license-allowlist.txt.
This gate never fabricates licenses — record the real upstream license.
EOF
  } >&2
  exit 1
fi

echo "resolve-license: PASS — every scanned asset has a license note."
