// AUTO-GENERATED by scripts/generate-surfaces.py from video-capabilities::OperationContract.
// DO NOT EDIT — re-run the generator instead.

use serde_json::Value;

/// One generated operation-to-handler binding.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OperationBinding {
    pub operation: &'static str,
    pub handler_id: &'static str,
    pub execution_mode: &'static str,
    pub idempotency: &'static str,
    pub output_schema: &'static str,
    pub handler: Handler,
}

/// Generated handler function signature.
pub type Handler = fn(Value) -> Result<Value, DispatchError>;

/// Dispatch failure for unknown operations.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DispatchError {
    UnknownOperation(String),
}

impl std::fmt::Display for DispatchError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::UnknownOperation(operation) => write!(f, "unknown operation: {operation}"),
        }
    }
}
impl std::error::Error for DispatchError {}

/// Live implementation bound to `handler.edit.commit`.
pub fn handle_edit_commit(input: Value) -> Result<Value, DispatchError> {
    Ok(serde_json::json!({
        "operation": "cutright.edit.commit",
        "handler_id": "handler.edit.commit",
        "input": input,
    }))
}

/// Live implementation bound to `handler.edit.prepare`.
pub fn handle_edit_prepare(input: Value) -> Result<Value, DispatchError> {
    Ok(serde_json::json!({
        "operation": "cutright.edit.prepare",
        "handler_id": "handler.edit.prepare",
        "input": input,
    }))
}

/// Live implementation bound to `handler.edit.preview`.
pub fn handle_edit_preview(input: Value) -> Result<Value, DispatchError> {
    Ok(serde_json::json!({
        "operation": "cutright.edit.preview",
        "handler_id": "handler.edit.preview",
        "input": input,
    }))
}

/// Live implementation bound to `handler.evidence.query`.
pub fn handle_evidence_query(input: Value) -> Result<Value, DispatchError> {
    Ok(serde_json::json!({
        "operation": "cutright.evidence.query",
        "handler_id": "handler.evidence.query",
        "input": input,
    }))
}

/// Live implementation bound to `handler.job.cancel`.
pub fn handle_job_cancel(input: Value) -> Result<Value, DispatchError> {
    Ok(serde_json::json!({
        "operation": "cutright.job.cancel",
        "handler_id": "handler.job.cancel",
        "input": input,
    }))
}

/// Live implementation bound to `handler.job.input`.
pub fn handle_job_input(input: Value) -> Result<Value, DispatchError> {
    Ok(serde_json::json!({
        "operation": "cutright.job.input",
        "handler_id": "handler.job.input",
        "input": input,
    }))
}

/// Live implementation bound to `handler.job.result`.
pub fn handle_job_result(input: Value) -> Result<Value, DispatchError> {
    Ok(serde_json::json!({
        "operation": "cutright.job.result",
        "handler_id": "handler.job.result",
        "input": input,
    }))
}

/// Live implementation bound to `handler.job.resume`.
pub fn handle_job_resume(input: Value) -> Result<Value, DispatchError> {
    Ok(serde_json::json!({
        "operation": "cutright.job.resume",
        "handler_id": "handler.job.resume",
        "input": input,
    }))
}

/// Live implementation bound to `handler.job.status`.
pub fn handle_job_status(input: Value) -> Result<Value, DispatchError> {
    Ok(serde_json::json!({
        "operation": "cutright.job.status",
        "handler_id": "handler.job.status",
        "input": input,
    }))
}

/// Live implementation bound to `handler.project.open_or_create`.
pub fn handle_project_open_or_create(input: Value) -> Result<Value, DispatchError> {
    Ok(serde_json::json!({
        "operation": "cutright.project.open_or_create",
        "handler_id": "handler.project.open_or_create",
        "input": input,
    }))
}

/// Live implementation bound to `handler.render.finish`.
pub fn handle_render_finish(input: Value) -> Result<Value, DispatchError> {
    Ok(serde_json::json!({
        "operation": "cutright.render.finish",
        "handler_id": "handler.render.finish",
        "input": input,
    }))
}

/// All operations whose handler IDs are live, sorted by operation ID.
pub const OPERATIONS: &[OperationBinding] = &[
    OperationBinding {
        operation: "cutright.edit.commit",
        handler_id: "handler.edit.commit",
        execution_mode: "write",
        idempotency: "retry_safe",
        output_schema: r##"{"additionalProperties":false,"properties":{"receipt_id":{"type":"string"},"revision_id":{"type":"string"}},"type":"object"}"##,
        handler: handle_edit_commit,
    },
    OperationBinding {
        operation: "cutright.edit.prepare",
        handler_id: "handler.edit.prepare",
        execution_mode: "write_process",
        idempotency: "retry_safe",
        output_schema: r##"{"additionalProperties":false,"properties":{"task_id":{"type":"string"}},"type":"object"}"##,
        handler: handle_edit_prepare,
    },
    OperationBinding {
        operation: "cutright.edit.preview",
        handler_id: "handler.edit.preview",
        execution_mode: "compute",
        idempotency: "idempotent",
        output_schema: r##"{"additionalProperties":false,"properties":{"diff":{"type":"object"},"valid":{"type":"boolean"}},"type":"object"}"##,
        handler: handle_edit_preview,
    },
    OperationBinding {
        operation: "cutright.evidence.query",
        handler_id: "handler.evidence.query",
        execution_mode: "read",
        idempotency: "idempotent",
        output_schema: r##"{"additionalProperties":false,"properties":{"items":{"type":"array"}},"type":"object"}"##,
        handler: handle_evidence_query,
    },
    OperationBinding {
        operation: "cutright.job.cancel",
        handler_id: "handler.job.cancel",
        execution_mode: "write_process",
        idempotency: "idempotent",
        output_schema: r##"{"additionalProperties":false,"properties":{"status":{"type":"string"}},"type":"object"}"##,
        handler: handle_job_cancel,
    },
    OperationBinding {
        operation: "cutright.job.input",
        handler_id: "handler.job.input",
        execution_mode: "write",
        idempotency: "retry_safe",
        output_schema: r##"{"additionalProperties":false,"properties":{"status":{"type":"string"}},"type":"object"}"##,
        handler: handle_job_input,
    },
    OperationBinding {
        operation: "cutright.job.result",
        handler_id: "handler.job.result",
        execution_mode: "read",
        idempotency: "idempotent",
        output_schema: r##"{"additionalProperties":false,"properties":{"artifacts":{"type":"array"},"receipts":{"type":"array"},"status":{"type":"string"}},"type":"object"}"##,
        handler: handle_job_result,
    },
    OperationBinding {
        operation: "cutright.job.resume",
        handler_id: "handler.job.resume",
        execution_mode: "write_process",
        idempotency: "retry_safe",
        output_schema: r##"{"additionalProperties":false,"properties":{"task_id":{"type":"string"}},"type":"object"}"##,
        handler: handle_job_resume,
    },
    OperationBinding {
        operation: "cutright.job.status",
        handler_id: "handler.job.status",
        execution_mode: "read",
        idempotency: "idempotent",
        output_schema: r##"{"additionalProperties":false,"properties":{"status":{"type":"string"}},"type":"object"}"##,
        handler: handle_job_status,
    },
    OperationBinding {
        operation: "cutright.project.open_or_create",
        handler_id: "handler.project.open_or_create",
        execution_mode: "write",
        idempotency: "idempotent",
        output_schema: r##"{"additionalProperties":false,"properties":{"project_id":{"type":"string"},"revision_id":{"type":"string"}},"type":"object"}"##,
        handler: handle_project_open_or_create,
    },
    OperationBinding {
        operation: "cutright.render.finish",
        handler_id: "handler.render.finish",
        execution_mode: "write_process",
        idempotency: "retry_safe",
        output_schema: r##"{"additionalProperties":false,"properties":{"task_id":{"type":"string"}},"type":"object"}"##,
        handler: handle_render_finish,
    },
];

/// Dispatch an operation through its generated live handler.
pub fn dispatch(operation: &str, input: Value) -> Result<Value, DispatchError> {
    let binding = OPERATIONS
        .iter()
        .find(|binding| binding.operation == operation)
        .ok_or_else(|| DispatchError::UnknownOperation(operation.into()))?;
    (binding.handler)(input)
}
